server:
  port: 8081
spring:
  application:
    name: "solicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

  flyway:
    enabled: true
    # Flyway usar√° su propio DataSource JDBC si se provee esta URL
    url: "jdbc:mysql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}"
    user: "${adapters.r2dbc.username}"
    password: "${adapters.r2dbc.password}"
    locations: "classpath:db/migration"
    connect-retries: 3
    placeholders:
      db: "${adapters.r2dbc.database}"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

r2dbc:
  url: "r2dbc:mysql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}"
  username: "${adapters.r2dbc.username}"
  password: "${adapters.r2dbc.password}"
  pool:
    initial-size: 5
    max-size: 20
    max-idle-time: 30m


adapters:
  r2dbc:
    host: "localhost"
    port: 3306
    database: "solicitudes"
    username: "root"
    password: "andres98"
  authentication:
    base-url: "http://localhost:8080"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

# Logging Configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS-05:00}  %5p %d{pid} --- [%15.15t] %-40.40logger{39} : %m%n"
  level:
    co.com.crediya.pragma.solicitudes: INFO
    org.springframework.web.reactive.function.client: DEBUG

# External Services Configuration

